In [1]:
# Import dependencies
import os
import pandas as pd
import numpy as np

In [3]:
## Read in data from file
df = pd.read_csv(os.path.join('thirdDown.csv'))
df.head()

,Unnamed: 0,play_id,game_id,shotgun,no_huddle,ydstogo,yardline_100,play_type,half_seconds_remaining,down,pass_length,pass_length.1,run_location,score_differential,fg_prob,td_prob,ep,third_down_converted
0,0,190,2018090600,1,0,10,39.0,pass,1681.0,3.0,deep,deep,NaN,0.0,0.415009,0.333712,2.250232,1.0
1,1,256,2018090600,1,0,1,1.0,pass,1559.0,3.0,short,short,NaN,0.0,0.204515,0.749825,5.661931,0.0
2,2,344,2018090600,1,0,4,92.0,pass,1464.0,3.0,short,short,NaN,0.0,0.093928,0.213978,-1.832560,0.0
3,3,445,2018090600,1,0,5,39.0,run,1404.0,3.0,NaN,NaN,right,0.0,0.395592,0.377457,2.642543,1.0
4,4,636,2018090600,1,0,3,3.0,pass,1207.0,3.0,short,short,NaN,0.0,0.386222,0.567801,4.926552,0.0

In [8]:
df.dtypes

Unnamed: 0                  int64
play_id                     int64
game_id                     int64
shotgun                     int64
no_huddle                   int64
ydstogo                     int64
yardline_100              float64
play_type                  object
half_seconds_remaining    float64
down                      float64
pass_length                object
pass_length.1              object
run_location               object
score_differential        float64
fg_prob                   float64
td_prob                   float64
ep                        float64
third_down_converted      float64
dtype: object

In [22]:
# Trim 
trimDF = df.drop(columns = ['play_id', 'game_id', 'Unnamed: 0'])

In [23]:
trimDF.head()

,shotgun,no_huddle,ydstogo,yardline_100,play_type,half_seconds_remaining,down,pass_length,pass_length.1,run_location,score_differential,fg_prob,td_prob,ep,third_down_converted
0,1,0,10,39.0,pass,1681.0,3.0,deep,deep,NaN,0.0,0.415009,0.333712,2.250232,1.0
1,1,0,1,1.0,pass,1559.0,3.0,short,short,NaN,0.0,0.204515,0.749825,5.661931,0.0
2,1,0,4,92.0,pass,1464.0,3.0,short,short,NaN,0.0,0.093928,0.213978,-1.832560,0.0
3,1,0,5,39.0,run,1404.0,3.0,NaN,NaN,right,0.0,0.395592,0.377457,2.642543,1.0
4,1,0,3,3.0,pass,1207.0,3.0,short,short,NaN,0.0,0.386222,0.567801,4.926552,0.0

In [31]:
# Separate by success
successDF = trimDF.loc[trimDF['third_down_converted']== 1.0]

In [27]:
failDF = trimDF['third_down_converted' == 0.0]

KeyError: False